// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Immutable = require("../src/immutable.bs.js");

var t1 = [1];

var t2 = Immutable.$$Array.head(Immutable.$$Array.fromArray(t1));

var t4 = Immutable.$$Array.tail(Immutable.$$Array.fromArray(t1));

var t5 = {};

var t6 = Immutable.Dict.set(Immutable.Dict.make(t5), "t", 1);

var t10 = Immutable.Dict.make(Object.fromEntries([[
            "foo",
            "bar"
          ]]));

var t11 = Immutable.$$Array.fromArray(t1);

var t12 = Immutable.$$Array.at(t11, 1);

exports.t1 = t1;
exports.t2 = t2;
exports.t4 = t4;
exports.t5 = t5;
exports.t6 = t6;
exports.t10 = t10;
exports.t11 = t11;
exports.t12 = t12;
/* t2 Not a pure module */
